#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Project1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgestiuni(gestiuni instance);
    partial void Updategestiuni(gestiuni instance);
    partial void Deletegestiuni(gestiuni instance);
    partial void Insertintrari(intrari instance);
    partial void Updateintrari(intrari instance);
    partial void Deleteintrari(intrari instance);
    partial void Insertintrari_detaliu(intrari_detaliu instance);
    partial void Updateintrari_detaliu(intrari_detaliu instance);
    partial void Deleteintrari_detaliu(intrari_detaliu instance);
    partial void Insertparteneri(parteneri instance);
    partial void Updateparteneri(parteneri instance);
    partial void Deleteparteneri(parteneri instance);
    partial void Insertproduse(produse instance);
    partial void Updateproduse(produse instance);
    partial void Deleteproduse(produse instance);
    partial void Insertiesiri_detaliu(iesiri_detaliu instance);
    partial void Updateiesiri_detaliu(iesiri_detaliu instance);
    partial void Deleteiesiri_detaliu(iesiri_detaliu instance);
    partial void Insertiesiri(iesiri instance);
    partial void Updateiesiri(iesiri instance);
    partial void Deleteiesiri(iesiri instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp2.Properties.Settings.Default.DB_Project1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<gestiuni> gestiunis
		{
			get
			{
				return this.GetTable<gestiuni>();
			}
		}
		
		public System.Data.Linq.Table<intrari> intraris
		{
			get
			{
				return this.GetTable<intrari>();
			}
		}
		
		public System.Data.Linq.Table<intrari_detaliu> intrari_detalius
		{
			get
			{
				return this.GetTable<intrari_detaliu>();
			}
		}
		
		public System.Data.Linq.Table<parteneri> parteneris
		{
			get
			{
				return this.GetTable<parteneri>();
			}
		}
		
		public System.Data.Linq.Table<produse> produses
		{
			get
			{
				return this.GetTable<produse>();
			}
		}
		
		public System.Data.Linq.Table<iesiri_detaliu> iesiri_detalius
		{
			get
			{
				return this.GetTable<iesiri_detaliu>();
			}
		}
		
		public System.Data.Linq.Table<iesiri> iesiris
		{
			get
			{
				return this.GetTable<iesiri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gestiuni")]
	public partial class gestiuni : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private int _cod;
		
		private string _denumire;
		
		private EntitySet<intrari> _intraris;
		
		private EntitySet<iesiri> _iesiris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OncodChanging(int value);
    partial void OncodChanged();
    partial void OndenumireChanging(string value);
    partial void OndenumireChanged();
    #endregion
		
		public gestiuni()
		{
			this._intraris = new EntitySet<intrari>(new Action<intrari>(this.attach_intraris), new Action<intrari>(this.detach_intraris));
			this._iesiris = new EntitySet<iesiri>(new Action<iesiri>(this.attach_iesiris), new Action<iesiri>(this.detach_iesiris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this.OncodChanging(value);
					this.SendPropertyChanging();
					this._cod = value;
					this.SendPropertyChanged("cod");
					this.OncodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denumire", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string denumire
		{
			get
			{
				return this._denumire;
			}
			set
			{
				if ((this._denumire != value))
				{
					this.OndenumireChanging(value);
					this.SendPropertyChanging();
					this._denumire = value;
					this.SendPropertyChanged("denumire");
					this.OndenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gestiuni_intrari", Storage="_intraris", ThisKey="id", OtherKey="gestiune")]
		public EntitySet<intrari> intraris
		{
			get
			{
				return this._intraris;
			}
			set
			{
				this._intraris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gestiuni_iesiri", Storage="_iesiris", ThisKey="id", OtherKey="gestiunea")]
		public EntitySet<iesiri> iesiris
		{
			get
			{
				return this._iesiris;
			}
			set
			{
				this._iesiris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_intraris(intrari entity)
		{
			this.SendPropertyChanging();
			entity.gestiuni = this;
		}
		
		private void detach_intraris(intrari entity)
		{
			this.SendPropertyChanging();
			entity.gestiuni = null;
		}
		
		private void attach_iesiris(iesiri entity)
		{
			this.SendPropertyChanging();
			entity.gestiuni = this;
		}
		
		private void detach_iesiris(iesiri entity)
		{
			this.SendPropertyChanging();
			entity.gestiuni = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.intrari")]
	public partial class intrari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private decimal _numar;
		
		private System.Nullable<System.DateTime> _data;
		
		private System.Nullable<decimal> _partener;
		
		private System.Nullable<decimal> _gestiune;
		
		private EntitySet<intrari_detaliu> _intrari_detalius;
		
		private EntityRef<gestiuni> _gestiuni;
		
		private EntityRef<parteneri> _parteneri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnnumarChanging(decimal value);
    partial void OnnumarChanged();
    partial void OndataChanging(System.Nullable<System.DateTime> value);
    partial void OndataChanged();
    partial void OnpartenerChanging(System.Nullable<decimal> value);
    partial void OnpartenerChanged();
    partial void OngestiuneChanging(System.Nullable<decimal> value);
    partial void OngestiuneChanged();
    #endregion
		
		public intrari()
		{
			this._intrari_detalius = new EntitySet<intrari_detaliu>(new Action<intrari_detaliu>(this.attach_intrari_detalius), new Action<intrari_detaliu>(this.detach_intrari_detalius));
			this._gestiuni = default(EntityRef<gestiuni>);
			this._parteneri = default(EntityRef<parteneri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numar", DbType="Decimal(18,0) NOT NULL")]
		public decimal numar
		{
			get
			{
				return this._numar;
			}
			set
			{
				if ((this._numar != value))
				{
					this.OnnumarChanging(value);
					this.SendPropertyChanging();
					this._numar = value;
					this.SendPropertyChanged("numar");
					this.OnnumarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime")]
		public System.Nullable<System.DateTime> data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partener", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> partener
		{
			get
			{
				return this._partener;
			}
			set
			{
				if ((this._partener != value))
				{
					if (this._parteneri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnpartenerChanging(value);
					this.SendPropertyChanging();
					this._partener = value;
					this.SendPropertyChanged("partener");
					this.OnpartenerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gestiune", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> gestiune
		{
			get
			{
				return this._gestiune;
			}
			set
			{
				if ((this._gestiune != value))
				{
					if (this._gestiuni.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngestiuneChanging(value);
					this.SendPropertyChanging();
					this._gestiune = value;
					this.SendPropertyChanged("gestiune");
					this.OngestiuneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="intrari_intrari_detaliu", Storage="_intrari_detalius", ThisKey="id", OtherKey="id_intrari")]
		public EntitySet<intrari_detaliu> intrari_detalius
		{
			get
			{
				return this._intrari_detalius;
			}
			set
			{
				this._intrari_detalius.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gestiuni_intrari", Storage="_gestiuni", ThisKey="gestiune", OtherKey="id", IsForeignKey=true)]
		public gestiuni gestiuni
		{
			get
			{
				return this._gestiuni.Entity;
			}
			set
			{
				gestiuni previousValue = this._gestiuni.Entity;
				if (((previousValue != value) 
							|| (this._gestiuni.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gestiuni.Entity = null;
						previousValue.intraris.Remove(this);
					}
					this._gestiuni.Entity = value;
					if ((value != null))
					{
						value.intraris.Add(this);
						this._gestiune = value.id;
					}
					else
					{
						this._gestiune = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("gestiuni");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parteneri_intrari", Storage="_parteneri", ThisKey="partener", OtherKey="id", IsForeignKey=true)]
		public parteneri parteneri
		{
			get
			{
				return this._parteneri.Entity;
			}
			set
			{
				parteneri previousValue = this._parteneri.Entity;
				if (((previousValue != value) 
							|| (this._parteneri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._parteneri.Entity = null;
						previousValue.intraris.Remove(this);
					}
					this._parteneri.Entity = value;
					if ((value != null))
					{
						value.intraris.Add(this);
						this._partener = value.id;
					}
					else
					{
						this._partener = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("parteneri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_intrari_detalius(intrari_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.intrari = this;
		}
		
		private void detach_intrari_detalius(intrari_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.intrari = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.intrari_detaliu")]
	public partial class intrari_detaliu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _id_intrari;
		
		private System.Nullable<decimal> _produs;
		
		private System.Nullable<decimal> _cantitate;
		
		private System.Nullable<decimal> _valoare;
		
		private EntityRef<intrari> _intrari;
		
		private EntityRef<produse> _produse;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Onid_intrariChanging(System.Nullable<decimal> value);
    partial void Onid_intrariChanged();
    partial void OnprodusChanging(System.Nullable<decimal> value);
    partial void OnprodusChanged();
    partial void OncantitateChanging(System.Nullable<decimal> value);
    partial void OncantitateChanged();
    partial void OnvaloareChanging(System.Nullable<decimal> value);
    partial void OnvaloareChanged();
    #endregion
		
		public intrari_detaliu()
		{
			this._intrari = default(EntityRef<intrari>);
			this._produse = default(EntityRef<produse>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_intrari", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_intrari
		{
			get
			{
				return this._id_intrari;
			}
			set
			{
				if ((this._id_intrari != value))
				{
					if (this._intrari.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_intrariChanging(value);
					this.SendPropertyChanging();
					this._id_intrari = value;
					this.SendPropertyChanged("id_intrari");
					this.Onid_intrariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> produs
		{
			get
			{
				return this._produs;
			}
			set
			{
				if ((this._produs != value))
				{
					if (this._produse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnprodusChanging(value);
					this.SendPropertyChanging();
					this._produs = value;
					this.SendPropertyChanged("produs");
					this.OnprodusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantitate", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cantitate
		{
			get
			{
				return this._cantitate;
			}
			set
			{
				if ((this._cantitate != value))
				{
					this.OncantitateChanging(value);
					this.SendPropertyChanging();
					this._cantitate = value;
					this.SendPropertyChanged("cantitate");
					this.OncantitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoare", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valoare
		{
			get
			{
				return this._valoare;
			}
			set
			{
				if ((this._valoare != value))
				{
					this.OnvaloareChanging(value);
					this.SendPropertyChanging();
					this._valoare = value;
					this.SendPropertyChanged("valoare");
					this.OnvaloareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="intrari_intrari_detaliu", Storage="_intrari", ThisKey="id_intrari", OtherKey="id", IsForeignKey=true)]
		public intrari intrari
		{
			get
			{
				return this._intrari.Entity;
			}
			set
			{
				intrari previousValue = this._intrari.Entity;
				if (((previousValue != value) 
							|| (this._intrari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._intrari.Entity = null;
						previousValue.intrari_detalius.Remove(this);
					}
					this._intrari.Entity = value;
					if ((value != null))
					{
						value.intrari_detalius.Add(this);
						this._id_intrari = value.id;
					}
					else
					{
						this._id_intrari = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("intrari");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produse_intrari_detaliu", Storage="_produse", ThisKey="produs", OtherKey="id", IsForeignKey=true)]
		public produse produse
		{
			get
			{
				return this._produse.Entity;
			}
			set
			{
				produse previousValue = this._produse.Entity;
				if (((previousValue != value) 
							|| (this._produse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produse.Entity = null;
						previousValue.intrari_detalius.Remove(this);
					}
					this._produse.Entity = value;
					if ((value != null))
					{
						value.intrari_detalius.Add(this);
						this._produs = value.id;
					}
					else
					{
						this._produs = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("produse");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.parteneri")]
	public partial class parteneri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private int _cod;
		
		private string _denumire;
		
		private string _cui;
		
		private string _adresa;
		
		private EntitySet<intrari> _intraris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OncodChanging(int value);
    partial void OncodChanged();
    partial void OndenumireChanging(string value);
    partial void OndenumireChanged();
    partial void OncuiChanging(string value);
    partial void OncuiChanged();
    partial void OnadresaChanging(string value);
    partial void OnadresaChanged();
    #endregion
		
		public parteneri()
		{
			this._intraris = new EntitySet<intrari>(new Action<intrari>(this.attach_intraris), new Action<intrari>(this.detach_intraris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this.OncodChanging(value);
					this.SendPropertyChanging();
					this._cod = value;
					this.SendPropertyChanged("cod");
					this.OncodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denumire", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string denumire
		{
			get
			{
				return this._denumire;
			}
			set
			{
				if ((this._denumire != value))
				{
					this.OndenumireChanging(value);
					this.SendPropertyChanging();
					this._denumire = value;
					this.SendPropertyChanged("denumire");
					this.OndenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cui", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string cui
		{
			get
			{
				return this._cui;
			}
			set
			{
				if ((this._cui != value))
				{
					this.OncuiChanging(value);
					this.SendPropertyChanging();
					this._cui = value;
					this.SendPropertyChanged("cui");
					this.OncuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresa", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string adresa
		{
			get
			{
				return this._adresa;
			}
			set
			{
				if ((this._adresa != value))
				{
					this.OnadresaChanging(value);
					this.SendPropertyChanging();
					this._adresa = value;
					this.SendPropertyChanged("adresa");
					this.OnadresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="parteneri_intrari", Storage="_intraris", ThisKey="id", OtherKey="partener")]
		public EntitySet<intrari> intraris
		{
			get
			{
				return this._intraris;
			}
			set
			{
				this._intraris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_intraris(intrari entity)
		{
			this.SendPropertyChanging();
			entity.parteneri = this;
		}
		
		private void detach_intraris(intrari entity)
		{
			this.SendPropertyChanging();
			entity.parteneri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produse")]
	public partial class produse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private int _cod;
		
		private string _denumire;
		
		private System.Nullable<decimal> _pret_unitar;
		
		private EntitySet<intrari_detaliu> _intrari_detalius;
		
		private EntitySet<iesiri_detaliu> _iesiri_detalius;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OncodChanging(int value);
    partial void OncodChanged();
    partial void OndenumireChanging(string value);
    partial void OndenumireChanged();
    partial void Onpret_unitarChanging(System.Nullable<decimal> value);
    partial void Onpret_unitarChanged();
    #endregion
		
		public produse()
		{
			this._intrari_detalius = new EntitySet<intrari_detaliu>(new Action<intrari_detaliu>(this.attach_intrari_detalius), new Action<intrari_detaliu>(this.detach_intrari_detalius));
			this._iesiri_detalius = new EntitySet<iesiri_detaliu>(new Action<iesiri_detaliu>(this.attach_iesiri_detalius), new Action<iesiri_detaliu>(this.detach_iesiri_detalius));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod", DbType="Int NOT NULL")]
		public int cod
		{
			get
			{
				return this._cod;
			}
			set
			{
				if ((this._cod != value))
				{
					this.OncodChanging(value);
					this.SendPropertyChanging();
					this._cod = value;
					this.SendPropertyChanged("cod");
					this.OncodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_denumire", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string denumire
		{
			get
			{
				return this._denumire;
			}
			set
			{
				if ((this._denumire != value))
				{
					this.OndenumireChanging(value);
					this.SendPropertyChanging();
					this._denumire = value;
					this.SendPropertyChanged("denumire");
					this.OndenumireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pret_unitar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pret_unitar
		{
			get
			{
				return this._pret_unitar;
			}
			set
			{
				if ((this._pret_unitar != value))
				{
					this.Onpret_unitarChanging(value);
					this.SendPropertyChanging();
					this._pret_unitar = value;
					this.SendPropertyChanged("pret_unitar");
					this.Onpret_unitarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produse_intrari_detaliu", Storage="_intrari_detalius", ThisKey="id", OtherKey="produs")]
		public EntitySet<intrari_detaliu> intrari_detalius
		{
			get
			{
				return this._intrari_detalius;
			}
			set
			{
				this._intrari_detalius.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produse_iesiri_detaliu", Storage="_iesiri_detalius", ThisKey="id", OtherKey="produs")]
		public EntitySet<iesiri_detaliu> iesiri_detalius
		{
			get
			{
				return this._iesiri_detalius;
			}
			set
			{
				this._iesiri_detalius.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_intrari_detalius(intrari_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.produse = this;
		}
		
		private void detach_intrari_detalius(intrari_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.produse = null;
		}
		
		private void attach_iesiri_detalius(iesiri_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.produse = this;
		}
		
		private void detach_iesiri_detalius(iesiri_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.produse = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iesiri_detaliu")]
	public partial class iesiri_detaliu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _id_iesiri;
		
		private System.Nullable<decimal> _produs;
		
		private System.Nullable<decimal> _cantitate;
		
		private System.Nullable<decimal> _valoare;
		
		private EntityRef<produse> _produse;
		
		private EntityRef<iesiri> _iesiri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Onid_iesiriChanging(System.Nullable<decimal> value);
    partial void Onid_iesiriChanged();
    partial void OnprodusChanging(System.Nullable<decimal> value);
    partial void OnprodusChanged();
    partial void OncantitateChanging(System.Nullable<decimal> value);
    partial void OncantitateChanged();
    partial void OnvaloareChanging(System.Nullable<decimal> value);
    partial void OnvaloareChanged();
    #endregion
		
		public iesiri_detaliu()
		{
			this._produse = default(EntityRef<produse>);
			this._iesiri = default(EntityRef<iesiri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_iesiri", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> id_iesiri
		{
			get
			{
				return this._id_iesiri;
			}
			set
			{
				if ((this._id_iesiri != value))
				{
					if (this._iesiri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_iesiriChanging(value);
					this.SendPropertyChanging();
					this._id_iesiri = value;
					this.SendPropertyChanged("id_iesiri");
					this.Onid_iesiriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> produs
		{
			get
			{
				return this._produs;
			}
			set
			{
				if ((this._produs != value))
				{
					if (this._produse.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnprodusChanging(value);
					this.SendPropertyChanging();
					this._produs = value;
					this.SendPropertyChanged("produs");
					this.OnprodusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantitate", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> cantitate
		{
			get
			{
				return this._cantitate;
			}
			set
			{
				if ((this._cantitate != value))
				{
					this.OncantitateChanging(value);
					this.SendPropertyChanging();
					this._cantitate = value;
					this.SendPropertyChanged("cantitate");
					this.OncantitateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valoare", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> valoare
		{
			get
			{
				return this._valoare;
			}
			set
			{
				if ((this._valoare != value))
				{
					this.OnvaloareChanging(value);
					this.SendPropertyChanging();
					this._valoare = value;
					this.SendPropertyChanged("valoare");
					this.OnvaloareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produse_iesiri_detaliu", Storage="_produse", ThisKey="produs", OtherKey="id", IsForeignKey=true)]
		public produse produse
		{
			get
			{
				return this._produse.Entity;
			}
			set
			{
				produse previousValue = this._produse.Entity;
				if (((previousValue != value) 
							|| (this._produse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._produse.Entity = null;
						previousValue.iesiri_detalius.Remove(this);
					}
					this._produse.Entity = value;
					if ((value != null))
					{
						value.iesiri_detalius.Add(this);
						this._produs = value.id;
					}
					else
					{
						this._produs = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("produse");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iesiri_iesiri_detaliu", Storage="_iesiri", ThisKey="id_iesiri", OtherKey="id", IsForeignKey=true)]
		public iesiri iesiri
		{
			get
			{
				return this._iesiri.Entity;
			}
			set
			{
				iesiri previousValue = this._iesiri.Entity;
				if (((previousValue != value) 
							|| (this._iesiri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._iesiri.Entity = null;
						previousValue.iesiri_detalius.Remove(this);
					}
					this._iesiri.Entity = value;
					if ((value != null))
					{
						value.iesiri_detalius.Add(this);
						this._id_iesiri = value.id;
					}
					else
					{
						this._id_iesiri = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("iesiri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.iesiri")]
	public partial class iesiri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private System.Nullable<decimal> _numar;
		
		private System.Nullable<System.DateTime> _data;
		
		private System.Nullable<decimal> _gestiunea;
		
		private EntitySet<iesiri_detaliu> _iesiri_detalius;
		
		private EntityRef<gestiuni> _gestiuni;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OnnumarChanging(System.Nullable<decimal> value);
    partial void OnnumarChanged();
    partial void OndataChanging(System.Nullable<System.DateTime> value);
    partial void OndataChanged();
    partial void OngestiuneaChanging(System.Nullable<decimal> value);
    partial void OngestiuneaChanged();
    #endregion
		
		public iesiri()
		{
			this._iesiri_detalius = new EntitySet<iesiri_detaliu>(new Action<iesiri_detaliu>(this.attach_iesiri_detalius), new Action<iesiri_detaliu>(this.detach_iesiri_detalius));
			this._gestiuni = default(EntityRef<gestiuni>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numar", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> numar
		{
			get
			{
				return this._numar;
			}
			set
			{
				if ((this._numar != value))
				{
					this.OnnumarChanging(value);
					this.SendPropertyChanging();
					this._numar = value;
					this.SendPropertyChanged("numar");
					this.OnnumarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data", DbType="DateTime")]
		public System.Nullable<System.DateTime> data
		{
			get
			{
				return this._data;
			}
			set
			{
				if ((this._data != value))
				{
					this.OndataChanging(value);
					this.SendPropertyChanging();
					this._data = value;
					this.SendPropertyChanged("data");
					this.OndataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gestiunea", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> gestiunea
		{
			get
			{
				return this._gestiunea;
			}
			set
			{
				if ((this._gestiunea != value))
				{
					if (this._gestiuni.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OngestiuneaChanging(value);
					this.SendPropertyChanging();
					this._gestiunea = value;
					this.SendPropertyChanged("gestiunea");
					this.OngestiuneaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="iesiri_iesiri_detaliu", Storage="_iesiri_detalius", ThisKey="id", OtherKey="id_iesiri")]
		public EntitySet<iesiri_detaliu> iesiri_detalius
		{
			get
			{
				return this._iesiri_detalius;
			}
			set
			{
				this._iesiri_detalius.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="gestiuni_iesiri", Storage="_gestiuni", ThisKey="gestiunea", OtherKey="id", IsForeignKey=true)]
		public gestiuni gestiuni
		{
			get
			{
				return this._gestiuni.Entity;
			}
			set
			{
				gestiuni previousValue = this._gestiuni.Entity;
				if (((previousValue != value) 
							|| (this._gestiuni.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._gestiuni.Entity = null;
						previousValue.iesiris.Remove(this);
					}
					this._gestiuni.Entity = value;
					if ((value != null))
					{
						value.iesiris.Add(this);
						this._gestiunea = value.id;
					}
					else
					{
						this._gestiunea = default(Nullable<decimal>);
					}
					this.SendPropertyChanged("gestiuni");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_iesiri_detalius(iesiri_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.iesiri = this;
		}
		
		private void detach_iesiri_detalius(iesiri_detaliu entity)
		{
			this.SendPropertyChanging();
			entity.iesiri = null;
		}
	}
}
#pragma warning restore 1591
